/*
 * decoder_config.h
 *
 *  Created on: Dec 25, 2021
 *      Author: Mohamed Hamada
 */

#ifndef HAL_22_DECODER_DECODER_CONFIG_H_
#define HAL_22_DECODER_DECODER_CONFIG_H_

#define NUM_OF_INPUT		2
#define NUM_OF_OUTPUT		pow(2,NUM_OF_INPUT)

#if NUM_OF_INPUT == 1
	#define DECODER_INPUT_1_PORT		PORT_C
	#define DECODER_INPUT_1_PIN			PIN_0

#elif NUM_OF_INPUT == 2
	#define DECODER_INPUT_1_PORT		PORT_C
	#define DECODER_INPUT_1_PIN			PIN_0
	#define DECODER_INPUT_2_PORT		PORT_C
	#define DECODER_INPUT_2_PIN			PIN_1
#elif NUM_OF_INPUT == 3
	#define DECODER_INPUT_1_PORT		PORT_C
	#define DECODER_INPUT_1_PIN			PIN_0
	#define DECODER_INPUT_2_PORT		PORT_C
	#define DECODER_INPUT_2_PIN			PIN_1
	#define DECODER_INPUT_3_PORT		PORT_C
	#define DECODER_INPUT_4_PIN			PIN_2
#elif NUM_OF_INPUT == 4
	#define DECODER_INPUT_1_PORT		PORT_C
	#define DECODER_INPUT_1_PIN			PIN_0
	#define DECODER_INPUT_2_PORT		PORT_C
	#define DECODER_INPUT_2_PIN			PIN_1
	#define DECODER_INPUT_3_PORT		PORT_C
	#define DECODER_INPUT_3_PIN			PIN_2
	#define DECODER_INPUT_4_PORT		PORT_C
	#define DECODER_INPUT_4_PIN			PIN_3
#elif NUM_OF_INPUT == 5
	#define DECODER_INPUT_1_PORT		PORT_C
	#define DECODER_INPUT_1_PIN			PIN_0
	#define DECODER_INPUT_2_PORT		PORT_C
	#define DECODER_INPUT_2_PIN			PIN_1
	#define DECODER_INPUT_3_PORT		PORT_C
	#define DECODER_INPUT_3_PIN			PIN_2
	#define DECODER_INPUT_4_PORT		PORT_C
	#define DECODER_INPUT_4_PIN			PIN_3
	#define DECODER_INPUT_5_PORT		PORT_C
	#define DECODER_INPUT_5_PIN			PIN_4
#elif NUM_OF_INPUT == 6
	#define DECODER_INPUT_1_PORT		PORT_C
	#define DECODER_INPUT_1_PIN			PIN_0
	#define DECODER_INPUT_2_PORT		PORT_C
	#define DECODER_INPUT_2_PIN			PIN_1
	#define DECODER_INPUT_3_PORT		PORT_C
	#define DECODER_INPUT_3_PIN			PIN_2
	#define DECODER_INPUT_4_PORT		PORT_C
	#define DECODER_INPUT_4_PIN			PIN_3
	#define DECODER_INPUT_5_PORT		PORT_C
	#define DECODER_INPUT_5_PIN			PIN_4
	#define DECODER_INPUT_6_PORT		PORT_C
	#define DECODER_INPUT_6_PIN			PIN_5
#endif
#endif /* 02_HAL_22_DECODER_DECODER_CONFIG_H_ */
