/*
 * multiplexer_config.h
 *
 *  Created on: Dec 25, 2021
 *      Author: Mohamed Hamada
 */

#ifndef HAL_21_MULTIPLEXER_MULTIPLEXER_CONFIG_H_
#define HAL_21_MULTIPLEXER_MULTIPLEXER_CONFIG_H_

#define NUM_OF_SELECT		2
#define NUM_OF_INPUT		pow(2,NUM_OF_SELECT)

#if NUM_OF_SELECT == 1
	#define MULTOPLEXER_SELECT_1_PORT		PORT_C
	#define MULTOPLEXER_SELECT_1_PIN			PIN_0

#elif NUM_OF_SELECT == 2
	#define MULTOPLEXER_SELECT_1_PORT		PORT_C
	#define MULTOPLEXER_SELECT_1_PIN			PIN_0
	#define MULTOPLEXER_SELECT_2_PORT		PORT_C
	#define MULTOPLEXER_SELECT_2_PIN			PIN_1
#elif NUM_OF_SELECT == 3
	#define MULTOPLEXER_SELECT_1_PORT		PORT_C
	#define MULTOPLEXER_SELECT_1_PIN			PIN_0
	#define MULTOPLEXER_SELECT_2_PORT		PORT_C
	#define MULTOPLEXER_SELECT_2_PIN			PIN_1
	#define MULTOPLEXER_SELECT_3_PORT		PORT_C
	#define MULTOPLEXER_SELECT_4_PIN			PIN_2
#elif NUM_OF_SELECT == 4
	#define MULTOPLEXER_SELECT_1_PORT		PORT_C
	#define MULTOPLEXER_SELECT_1_PIN			PIN_0
	#define MULTOPLEXER_SELECT_2_PORT		PORT_C
	#define MULTOPLEXER_SELECT_2_PIN			PIN_1
	#define MULTOPLEXER_SELECT_3_PORT		PORT_C
	#define MULTOPLEXER_SELECT_3_PIN			PIN_2
	#define MULTOPLEXER_SELECT_4_PORT		PORT_C
	#define MULTOPLEXER_SELECT_4_PIN			PIN_3
#elif NUM_OF_SELECT == 5
	#define MULTOPLEXER_SELECT_1_PORT		PORT_C
	#define MULTOPLEXER_SELECT_1_PIN			PIN_0
	#define MULTOPLEXER_SELECT_2_PORT		PORT_C
	#define MULTOPLEXER_SELECT_2_PIN			PIN_1
	#define MULTOPLEXER_SELECT_3_PORT		PORT_C
	#define MULTOPLEXER_SELECT_3_PIN			PIN_2
	#define MULTOPLEXER_SELECT_4_PORT		PORT_C
	#define MULTOPLEXER_SELECT_4_PIN			PIN_3
	#define MULTOPLEXER_SELECT_5_PORT		PORT_C
	#define MULTOPLEXER_SELECT_5_PIN			PIN_4
#elif NUM_OF_SELECT == 6
	#define MULTOPLEXER_SELECT_1_PORT		PORT_C
	#define MULTOPLEXER_SELECT_1_PIN			PIN_0
	#define MULTOPLEXER_SELECT_2_PORT		PORT_C
	#define MULTOPLEXER_SELECT_2_PIN			PIN_1
	#define MULTOPLEXER_SELECT_3_PORT		PORT_C
	#define MULTOPLEXER_SELECT_3_PIN			PIN_2
	#define MULTOPLEXER_SELECT_4_PORT		PORT_C
	#define MULTOPLEXER_SELECT_4_PIN			PIN_3
	#define MULTOPLEXER_SELECT_5_PORT		PORT_C
	#define MULTOPLEXER_SELECT_5_PIN			PIN_4
	#define MULTOPLEXER_SELECT_6_PORT		PORT_C
	#define MULTOPLEXER_SELECT_6_PIN			PIN_5
#endif


#endif /* 02_HAL_21_MULTIPLEXER_MULTIPLEXER_CONFIG_H_ */
